In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("India_FinTech_Fraud_Analytics_50000.csv")
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Amount_INR,Transaction_Type,Payment_Method,Merchant_Category,City,State,PIN_Code,Bank,Device_Type,Customer_Age,Account_Age_Days,Transaction_Status,Is_Fraud,Fraud_Type
0,TXN1012102,CUST13384,2025-01-01 01:01:09,2497.38,P2P Transfer,UPI,Healthcare,Bengaluru,Karnataka,742289,Yes Bank,iOS,49,1012,Success,0,NaN
1,TXN1029202,CUST12165,2025-01-01 01:20:04,5105.00,P2P Transfer,Debit Card,Education,Lucknow,Uttar Pradesh,295352,HDFC Bank,Android,23,1283,Success,0,NaN
2,TXN1010874,CUST13768,2025-01-01 01:20:33,764.33,Purchase,UPI,Food & Dining,Bengaluru,Karnataka,298601,ICICI Bank,ATM,54,3257,Success,0,NaN
3,TXN1049195,CUST12300,2025-01-01 02:05:58,3352.86,P2P Transfer,UPI,Grocery,Indore,Madhya Pradesh,616929,IndusInd Bank,Web,21,2132,Success,0,NaN
4,TXN1044846,CUST10831,2025-01-01 02:09:58,562.47,Bill Payment,UPI,Electronics,Patna,Bihar,160232,Kotak Mahindra Bank,Android,19,428,Success,0,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      50000 non-null  object
 1   Customer_ID         50000 non-null  object
 2   Transaction_Date    50000 non-null  object
 3   Amount_INR          50000 non-null  float64
 4   Transaction_Type    50000 non-null  object
 5   Payment_Method      50000 non-null  object
 6   Merchant_Category   50000 non-null  object
 7   City                50000 non-null  object
 8   State               50000 non-null  object
 9   PIN_Code            50000 non-null  int64
 10  Bank                50000 non-null  object
 11  Device_Type         50000 non-null  object
 12  Customer_Age        50000 non-null  int64
 13  Account_Age_Days    50000 non-null  int64
 14  Transaction_Status  50000 non-null  object
 15  Is_Fraud            50000 non-null  int64
 16  Fraud_Type          899 non-null    object
dtypes: float64(1), int64(4), object(12)
memory usage: 6.5+ MB

In [4]:
print(df.isnull().sum())

Transaction_ID            0
Customer_ID               0
Transaction_Date          0
Amount_INR                0
Transaction_Type          0
Payment_Method            0
Merchant_Category         0
City                      0
State                     0
PIN_Code                  0
Bank                      0
Device_Type               0
Customer_Age              0
Account_Age_Days          0
Transaction_Status        0
Is_Fraud                  0
Fraud_Type            49101
dtype: int64

In [5]:
df['Fraud_Type']= df['Fraud_Type'].fillna('Not Fraud')

In [6]:
print(df.isnull().sum())

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Amount_INR            0
Transaction_Type      0
Payment_Method        0
Merchant_Category     0
City                  0
State                 0
PIN_Code              0
Bank                  0
Device_Type           0
Customer_Age          0
Account_Age_Days      0
Transaction_Status    0
Is_Fraud              0
Fraud_Type            0
dtype: int64

In [7]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Amount_INR,Transaction_Type,Payment_Method,Merchant_Category,City,State,PIN_Code,Bank,Device_Type,Customer_Age,Account_Age_Days,Transaction_Status,Is_Fraud,Fraud_Type
0,TXN1012102,CUST13384,2025-01-01 01:01:09,2497.38,P2P Transfer,UPI,Healthcare,Bengaluru,Karnataka,742289,Yes Bank,iOS,49,1012,Success,0,Not Fraud
1,TXN1029202,CUST12165,2025-01-01 01:20:04,5105.00,P2P Transfer,Debit Card,Education,Lucknow,Uttar Pradesh,295352,HDFC Bank,Android,23,1283,Success,0,Not Fraud
2,TXN1010874,CUST13768,2025-01-01 01:20:33,764.33,Purchase,UPI,Food & Dining,Bengaluru,Karnataka,298601,ICICI Bank,ATM,54,3257,Success,0,Not Fraud
3,TXN1049195,CUST12300,2025-01-01 02:05:58,3352.86,P2P Transfer,UPI,Grocery,Indore,Madhya Pradesh,616929,IndusInd Bank,Web,21,2132,Success,0,Not Fraud
4,TXN1044846,CUST10831,2025-01-01 02:09:58,562.47,Bill Payment,UPI,Electronics,Patna,Bihar,160232,Kotak Mahindra Bank,Android,19,428,Success,0,Not Fraud

In [8]:
df.duplicated().sum()

0

In [9]:
df['Transaction_Date']= pd.to_datetime(df['Transaction_Date'])

In [10]:
df.dtypes

Transaction_ID                object
Customer_ID                   object
Transaction_Date      datetime64[ns]
Amount_INR                   float64
Transaction_Type              object
Payment_Method                object
Merchant_Category             object
City                          object
State                         object
PIN_Code                       int64
Bank                          object
Device_Type                   object
Customer_Age                   int64
Account_Age_Days               int64
Transaction_Status            object
Is_Fraud                       int64
Fraud_Type                    object
dtype: object

In [11]:
df.describe()

,Transaction_Date,Amount_INR,PIN_Code,Customer_Age,Account_Age_Days,Is_Fraud
count,50000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000
mean,2025-10-31 16:45:49.974419968,1577.581170,504565.259800,44.008120,1837.466700,0.01798
min,2025-01-01 01:01:09,50.000000,110015.000000,18.000000,30.000000,0.00000
25%,2025-06-01 18:52:40.750000128,620.340000,307785.750000,31.000000,927.000000,0.00000
50%,2025-10-31 23:47:53,1098.940000,503839.000000,44.000000,1837.500000,0.00000
75%,2026-04-02 01:09:53.249999872,1945.540000,702764.000000,57.000000,2743.000000,0.00000
max,2026-08-31 23:28:12,51522.890000,899998.000000,70.000000,3650.000000,1.00000
std,NaN,1652.705408,227938.105848,15.292537,1046.455745,0.13288

In [12]:
df.describe(include="object")

,Transaction_ID,Customer_ID,Transaction_Type,Payment_Method,Merchant_Category,City,State,Bank,Device_Type,Transaction_Status,Fraud_Type
count,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000
unique,50000,5000,5,5,10,20,12,8,4,3,6
top,TXN1012102,CUST13121,Purchase,UPI,Food & Dining,Bengaluru,Maharashtra,Kotak Mahindra Bank,Android,Success,Not Fraud
freq,1,24,23990,23916,5084,5015,12315,6345,24873,47431,49101

In [13]:
df['Payment_Method'].value_counts()

Payment_Method
UPI            23916
Debit Card     10038
Net Banking     6097
Credit Card     6067
Wallet          3882
Name: count, dtype: int64

In [14]:
df['Transaction_Type'].value_counts()

Transaction_Type
Purchase           23990
P2P Transfer       10041
Bill Payment        6009
Recharge            5104
Cash Withdrawal     4856
Name: count, dtype: int64

In [15]:
df['Is_Fraud'].value_counts()

Is_Fraud
0    49101
1      899
Name: count, dtype: int64

In [16]:
pd.crosstab(df['Payment_Method'],df['Is_Fraud'])

Is_Fraud            0    1
Payment_Method
Credit Card      5905  162
Debit Card       9880  158
Net Banking      6025   72
UPI             23546  370
Wallet           3745  137

In [17]:
fraud_by_payment= df.groupby('Payment_Method')['Is_Fraud'].mean()*100
fraud_by_payment.sort_values(ascending=False)

Payment_Method
Wallet         3.529109
Credit Card    2.670183
Debit Card     1.574019
UPI            1.547081
Net Banking    1.180909
Name: Is_Fraud, dtype: float64

In [18]:
fraud_by_state= df.groupby('State')['Is_Fraud'].mean()*100
fraud_by_state.sort_values(ascending=False)

State
Gujarat           2.083897
Madhya Pradesh    2.059117
Uttar Pradesh     2.009319
Rajasthan         1.944167
Delhi             1.830702
Telangana         1.821805
Bihar             1.780264
Tamil Nadu        1.723566
Maharashtra       1.721478
Kerala            1.656627
West Bengal       1.634103
Karnataka         1.607768
Name: Is_Fraud, dtype: float64

In [19]:
fraud_by_type= df.groupby('Transaction_Type')['Is_Fraud'].mean()*100
fraud_by_type.sort_values(ascending=False)

Transaction_Type
P2P Transfer       2.499751
Bill Payment       1.797304
Cash Withdrawal    1.729819
Recharge           1.567398
Purchase           1.567320
Name: Is_Fraud, dtype: float64

In [20]:
fraud_by_category= df.groupby('Merchant_Category')['Is_Fraud'].mean()*100
fraud_by_category.sort_values(ascending=False)

Merchant_Category
Grocery          2.371463
Education        1.864235
Utilities        1.862981
Retail           1.820364
Healthcare       1.818182
Electronics      1.801255
Entertainment    1.768489
E-commerce       1.721033
Food & Dining    1.553895
Travel           1.405106
Name: Is_Fraud, dtype: float64

In [21]:
fraud_by_Device_Type= df.groupby('Device_Type')['Is_Fraud'].mean()*100
fraud_by_Device_Type.sort_values(ascending=False)

Device_Type
Web        2.460073
Android    1.636312
iOS        1.625204
ATM        1.612103
Name: Is_Fraud, dtype: float64

In [22]:
import mysql.connector

In [23]:
mysql.connector.connect(
    host= "localhost",
    user= "root",
    password= "root"
)

In [24]:
df

,Transaction_ID,Customer_ID,Transaction_Date,Amount_INR,Transaction_Type,Payment_Method,Merchant_Category,City,State,PIN_Code,Bank,Device_Type,Customer_Age,Account_Age_Days,Transaction_Status,Is_Fraud,Fraud_Type
0,TXN1012102,CUST13384,2025-01-01 01:01:09,2497.38,P2P Transfer,UPI,Healthcare,Bengaluru,Karnataka,742289,Yes Bank,iOS,49,1012,Success,0,Not Fraud
1,TXN1029202,CUST12165,2025-01-01 01:20:04,5105.00,P2P Transfer,Debit Card,Education,Lucknow,Uttar Pradesh,295352,HDFC Bank,Android,23,1283,Success,0,Not Fraud
2,TXN1010874,CUST13768,2025-01-01 01:20:33,764.33,Purchase,UPI,Food & Dining,Bengaluru,Karnataka,298601,ICICI Bank,ATM,54,3257,Success,0,Not Fraud
3,TXN1049195,CUST12300,2025-01-01 02:05:58,3352.86,P2P Transfer,UPI,Grocery,Indore,Madhya Pradesh,616929,IndusInd Bank,Web,21,2132,Success,0,Not Fraud
4,TXN1044846,CUST10831,2025-01-01 02:09:58,562.47,Bill Payment,UPI,Electronics,Patna,Bihar,160232,Kotak Mahindra Bank,Android,19,428,Success,0,Not Fraud
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,TXN1040436,CUST13338,2026-08-31 21:38:24,3032.71,Purchase,Credit Card,Utilities,Jaipur,Rajasthan,499630,Bank of Baroda,Android,52,1567,Success,0,Not Fraud
49996,TXN1004513,CUST11055,2026-08-31 22:15:19,945.87,Cash Withdrawal,Debit Card,Travel,Mumbai,Maharashtra,767316,ICICI Bank,iOS,48,1138,Success,0,Not Fraud
49997,TXN1018135,CUST12523,2026-08-31 23:19:29,4028.25,Purchase,UPI,E-commerce,Mysuru,Karnataka,683408,IndusInd Bank,Android,45,2486,Success,0,Not Fraud
49998,TXN1027195,CUST11649,2026-08-31 23:22:52,477.59,Purchase,UPI,Electronics,Chennai,Tamil Nadu,799752,IndusInd Bank,Android,25,1888,Failed,0,Not Fraud
49999,TXN1040118,CUST10015,2026-08-31 23:28:12,649.09,Recharge,UPI,Food & Dining,Patna,Bihar,751362,IndusInd Bank,Web,32,2188,Success,0,Not Fraud

In [25]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\li\anaconda3\lib\site-packages (2.0.34)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\li\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\li\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [26]:
from sqlalchemy import create_engine

In [27]:
engine= create_engine(
    "mysql+pymysql://root:root@localhost/fintech_analytics"
)

In [28]:
connection= engine.connect()
print("MySQL connection successful")

MySQL connection successful

In [29]:
df.to_sql(
    name='transactions',
    con=engine,
    if_exists= 'append',
    index=False
)

50000